---

- name: Install Packages needed for load balancer setup
  yum:
    name: "{{ lb_tier_packages }}"
    state: latest

# job_temmplate QA is 11 - 04_3tier app deployment on QA Env - site-3tier-app.yml Play
# job_template PRO is 17 - 09_3 tier app on Prod

- name: Check Job_Template QA current running
  shell: tower-cli job list --status=running | awk '{ print $2 }' | grep -ci "11"
  register: current_env_qa

- name: Create haproxy configuration file QA
  template:
    src: haproxy.cfg.qa.j2
    dest: "{{ lb_tier_haproxy_config_file_path }}"
  notify:
    - restart haproxy
  when: "{{ current_env_qa | int }}" > 0  
  # if it doesn't return values then it's running prod job_template 

- name: Check Job_Template PRO current running
  shell: tower-cli job list --status=running | awk '{ print $2 }' | grep -ci "17"
  register: current_env_pro


- name: Create haproxy configuration file PRO
  template:
    src: haproxy.cfg.pro.j2
    dest: "{{ lb_tier_haproxy_config_file_path }}"
  notify:
    - restart haproxy
  when: "{{ current_env_pro | int }}" > 0
  # if it doesn't return values then it's running qa job_template

- name: Start and enable haproxy service
  service:
    name: "{{ lb_tier_haproxy_service_name }}"
    state: started
    enabled: true
...
